/** Original Rein workflows. Names identify guidance, not installed integrations. */
export interface OperatorPackSkill {
	name: string;
	description: string;
	body: string;
}

const guidance = (name: string, description: string, steps: string): OperatorPackSkill => Object.freeze({
	name,
	description,
	body: `# ${name}\n\nOriginal Rein-native workflow guidance. This is not an upstream ${name} skill or an installed external integration.\n\n${steps}\n\nUse only tools that are available. The current user request, project constraints, and tool approval settings take precedence. This workflow does not authorize unrelated work, install software, send messages, or bypass an approval.\n`,
});

export const OPERATOR_PACK_SKILLS: readonly OperatorPackSkill[] = Object.freeze([
	guidance("github-pr-workflow", "Prepare a focused change and a reviewable pull request when requested.", `Read the repository's contribution rules and current branch status. Make the smallest complete change and run the relevant checks. Inspect the final diff for unrelated files and secrets. If the user authorized publishing, use available GitHub tooling to create or update a pull request with the problem, result, and validation. Otherwise leave the local diff ready for review. Report the actual checks and pull request URL when one exists. This pack does not install GitHub tools or grant repository access.`),
	guidance("caveman", "Give concise answers that still include the result, evidence, and blockers.", `Lead with the result or next decision. Use short sentences and concrete names. Keep routine progress brief; give more detail when the user asks or when it is needed to understand a risk, failure, or choice. Never omit an unfinished step or failed check to make the answer shorter. Avoid roleplay, caricatures, and unexplained jargon.`),
	guidance("hermes-agent", "Complete authorized agent tasks with durable, verified notes.", `Read the user's task and current workspace evidence. Work in small steps, checking results before continuing. Use Rein's notes and history tools when available to recover decisions and retain verified facts. Keep secrets out of durable notes. Suggest a routine only when repeated work provides evidence for it; show its schedule, scope, and expected effects before enabling it. This is Rein guidance, not the Hermes agent, and it does not install Hermes or start a background service.`),
	guidance("fleet-command-ops", "Inspect explicitly selected hosts and report service health with evidence.", `Identify the hosts or services the user named and the access already available. Start with bounded status checks and logs. Separate confirmed failures from missing access. Before a change, identify impact, a rollback, and the check that will prove recovery. Run changes within the authorized scope and preserve approval gates. Do not scan unrelated reachable systems, copy credentials, or create persistent services merely because a host is accessible. This guidance supplies no fleet connection or SSH credentials.`),
	guidance("execution-discipline", "Track concrete outcomes and verify each before reporting completion.", `Turn a request with multiple parts into observable outcomes. Resolve dependencies in order and parallelize only independent work with available tools. Record a check for each material outcome. Stop repeated failing attempts, explain the evidence, and change the approach. Report what passed, what failed, and what remains. A plan or attempted command is not a completed result.`),
	guidance("grounded-citations", "Answer research questions with traceable sources and clear uncertainty.", `Define the question and locate relevant primary sources with available search or reading tools. Distinguish source findings from your own inference. Attach a direct source URL or local document reference to factual claims that depend on it. Check dates for changing information. Quote sparingly and state when evidence is missing or contradictory. If browsing is unavailable, say which sources you could read instead of inventing citations.`),
	guidance("plan", "Explain a task in ordered steps and make the next decision clear.", `Read the current task and relevant material. Give a short sequence of steps, explain why each matters, and identify checks for success. Ask for information only when it changes a consequential decision or blocks progress. Continue authorized independent work while a dependent step is waiting. Follow the user's requested level of explanation and revise the plan when evidence changes. This workflow does not change tool approval settings.`),
	guidance("claude-design", "Develop a visual direction and inspect the implemented result.", `Establish the audience, intended action, content, and brand constraints. Choose typography, spacing, contrast, and a visual direction that fit the task. Implement a focused draft using tools that are present; inspect the rendered result at relevant sizes and check readable text, keyboard navigation, and control states. Explain unfinished assets or interactions honestly. This is original Rein guidance, not a Claude integration, and it supplies no image model or design app.`),
	guidance("comfyui", "Prepare reproducible image workflows for an available ComfyUI installation.", `First establish whether the user has a ComfyUI instance and which nodes and models it provides. Use that evidence to prepare a workflow with explicit inputs, outputs, dimensions, and reproducibility settings. Do not invent installed models or custom nodes. When execution is available and authorized, inspect the result and adjust one material setting at a time. Otherwise provide a clearly labeled workflow plan or file and its missing prerequisites. This pack does not install ComfyUI, download model weights, or connect to a server.`),
]);
