/** Original Rein workflows. Each name identifies guidance, not an integration. */
export interface OperatorPackSkill {
	name: string;
	description: string;
	body: string;
}

const guidance = (name: string, description: string, steps: string): OperatorPackSkill => Object.freeze({
	name,
	description,
	body: `# ${name}\n\nOriginal Rein-native workflow guidance.\n\n${steps}\n\nUse only tools that are available. The current user request, project constraints, and tool approval settings take precedence. This workflow does not authorize unrelated work, install software, send messages, or bypass an approval.\n`,
});

export const OPERATOR_PACK_SKILLS: readonly OperatorPackSkill[] = Object.freeze([
	guidance("task-breakdown", "Turn an everyday goal into a small next action and a manageable checklist.", `Ask what a useful result would look like if it is unclear. Separate what the operator needs to do from work Rein can do with available tools. Make the next action concrete and small enough to start. Keep a short checklist for longer tasks, following the operator's pacing preference. Preserve decisions so they do not have to repeat them. Do not treat a stalled task as a personal failing or infer a diagnosis. Finish one useful outcome before expanding the task.`),
	guidance("routine-planning", "Prepare a simple routine from the operator's chosen goal and constraints.", `Start with a routine the operator actually wants: an evening checklist, document cleanup, weekly planning, or another recurring task. Identify the trigger, smallest useful action, and a simple check for success. Fit it to constraints the operator explicitly shared; do not infer a personal history. Offer a draft they can edit or skip. If a reminder or background job would help, show its scope, schedule, stop control, and required tools before enabling it with authorization. A written plan is not a scheduled reminder.`),
	guidance("decision-support", "Compare practical choices and explain why one fits the stated goal.", `Identify the decision, important constraints, and information that is actually missing. Compare a few viable options using those constraints. Recommend one with a brief reason and state meaningful uncertainty. Where prices, rules, or availability matter, verify them with available current sources. If the operator declines, ask what did not fit and offer the next suitable option; do not repeat or execute the rejected choice. Do not purchase, book, publish, or contact anyone just because a choice was discussed.`),
	guidance("code-change", "Prepare a focused code change and verify it with relevant checks.", `Read the repository's instructions and current branch status. Identify the smallest complete change that solves the user's problem. Preserve unrelated edits and inspect the final diff for secrets or accidental changes. Run the relevant checks and explain actual failures or limits. Create a commit, push, or prepare a pull request when authorized, using available tools. Report the concrete result and validation; a plan or attempted command is not completion.`),
	guidance("service-care", "Diagnose an explicitly selected service and make recoverable changes.", `Identify the host or service the operator selected and the access already available. Start with bounded status checks and relevant logs. Separate confirmed failures from missing access. Before a change, identify impact, a rollback, and the check that will prove recovery. Work within the authorized scope and preserve required approvals. Do not scan unrelated systems or create persistent services merely because a host is reachable.`),
	guidance("durable-notes", "Keep useful, verified decisions available across sessions.", `Use Rein's notes and history tools when available to recover the current task and confirmed decisions. Recheck facts that may have changed before acting. Save concise decisions, constraints, and useful recovery steps, with source or date when relevant. Keep credentials, unnecessary personal details, and unsupported inferences out of notes. Ask before changing the operator's enduring preferences. Explain which facts were recovered and which still need verification when that distinction affects the task.`),
	guidance("execution-discipline", "Track concrete outcomes and verify them before reporting completion.", `Turn a multi-part request into observable outcomes. Resolve dependencies in order and parallelize only independent work with available tools. Record a meaningful check for each material outcome. Stop repeated failing attempts, explain the evidence, and change the approach. Report what passed, what failed, and what remains. Keep plans brief and carry out already authorized work without seeking approval at every routine step.`),
	guidance("grounded-research", "Answer a research question with traceable sources and clear uncertainty.", `Define the question and locate relevant primary sources with available search or reading tools. Distinguish source findings from your own inference. Attach a direct source URL or local document reference to claims that depend on it. Check dates for changing information. Quote sparingly and state when evidence is missing or contradictory. If browsing is unavailable, explain which material you could read instead of inventing citations.`),
	guidance("learning-plan", "Work through a learning goal using examples and optional practice.", `Ask what the operator wants to understand or be able to do, and what they already know only when it changes the starting point. Prepare a short path to that goal. Follow their stated preferences for examples, pacing, explanation, and recaps; these are preferences, not fixed learning types. Offer a small worked example and an optional way to try it. Correct misunderstandings kindly using evidence. Do not grade ability or infer a diagnosis from responses.`),
	guidance("creative-brief", "Turn a creative idea into a clear, editable brief.", `Establish the intended audience, format, desired effect, content, and practical constraints. Use references the operator supplies and ask only about decisions that affect the result. Offer a small number of distinct directions and explain how each fits. Make a concrete draft with available tools and preserve editable source files when possible. State missing tools or assets honestly; do not claim image, audio, or video generation that has not happened.`),
	guidance("visual-review", "Inspect a produced visual or interface and make specific improvements.", `Inspect the actual artifact with available viewing tools. Check the intended message, visual hierarchy, readable text, contrast, spacing, and consistency. For an interface, also check relevant sizes, keyboard access, and control states. Separate observed defects from personal taste and propose a focused correction. Reinspect meaningful changes. If rendering or viewing is unavailable, state the limit instead of claiming visual verification.`),
]);
