// Dareecho brand gateway: the same-origin front for the Mastra Factory server.
//
// The Factory UI is generated by @mastra/factory and brands itself "Mastra
// Factory". This gateway sits in front of the server and presents the Dareecho
// OS identity instead — the title, the favicon, the theme color, a subtle brand
// stylesheet, and a rewritten web-app manifest ("Dareecho Factory", Dareecho
// icons) so that "Add to Home screen" installs a **Dareecho** launcher icon.
//
// It is transparent otherwise: every other request (assets, API, agent runs)
// proxies to the Factory server unchanged. Run it as the public entry point and
// point the Factory server at an internal port:
//
//   node apps/factory/brand-gateway.mjs --public 4111 --backend http://127.0.0.1:4112
//
// Keep this module Electron-free so the CLI and the test suite can run it under
// plain Node, exactly like the supervisor.
import http from "node:http";
import { createReadStream, existsSync, statSync } from "node:fs";
import { join, normalize, extname } from "node:path";
import { fileURLToPath } from "node:url";

const brandDir = join(fileURLToPath(new URL(".", import.meta.url)), "brand");

const CONTENT_TYPES = {
  ".svg": "image/svg+xml",
  ".css": "text/css; charset=utf-8",
  ".png": "image/png",
  ".json": "application/json; charset=utf-8",
  ".webmanifest": "application/manifest+json; charset=utf-8",
};

function parseArgs(argv) {
  const args = { publicPort: 4111, backend: "http://127.0.0.1:4112", host: "0.0.0.0" };
  for (let i = 0; i < argv.length; i += 1) {
    const a = argv[i];
    if (a === "--public") args.publicPort = Number(argv[++i]);
    else if (a === "--backend") args.backend = argv[++i];
    else if (a === "--host") args.host = argv[++i];
  }
  if (!Number.isSafeInteger(args.publicPort) || args.publicPort < 1) throw new Error("--public must be a port.");
  return args;
}

// Rewrite the generated Factory HTML to carry the Dareecho identity. The markup
// is a fixed, known shape; each replacement is idempotent and falls through to
// the original tag if a pattern is absent, so a Factory update cannot 500 here.
export function rebrand(html) {
  let out = String(html);
  out = out.replace(/<title>[\s\S]*?<\/title>/i, "<title>Dareecho Factory</title>");
  out = out.replace(/<link[^>]*rel=["']icon["'][^>]*>/i, '<link rel="icon" type="image/svg+xml" href="/dareecho/dareecho.svg" />');
  out = out.replace(/<link[^>]*rel=["']manifest["'][^>]*>/i, '<link rel="manifest" href="/dareecho/manifest.webmanifest" />');
  out = out.replace(/<link[^>]*rel=["']apple-touch-icon["'][^>]*>/i, '<link rel="apple-touch-icon" sizes="180x180" href="/dareecho/apple-180.png" />');
  out = out.replace(/<meta[^>]*name=["']theme-color["'][^>]*>/i, '<meta name="theme-color" content="#252a25" />');
  if (!out.includes("/dareecho/dareecho.css")) {
    out = out.replace(/<\/head>/i, '<link rel="stylesheet" href="/dareecho/dareecho.css" />\n  </head>');
  }
  return out;
}

// Map /dareecho/<file> to a file in the brand directory. The manifest is served
// from manifest.json as manifest.webmanifest so the link in the HTML is stable.
function brandPath(urlPath) {
  if (!urlPath.startsWith("/dareecho/")) return null;
  let file = urlPath.slice("/dareecho/".length);
  if (file === "manifest.webmanifest") file = "manifest.json";
  const full = normalize(join(brandDir, file));
  if (!full.startsWith(brandDir)) return null; // no traversal out of the brand dir
  return existsSync(full) && statSync(full).isFile() ? full : null;
}

function serveFile(res, filePath) {
  const type = CONTENT_TYPES[extname(filePath)] || "application/octet-stream";
  res.writeHead(200, { "Content-Type": type, "Cache-Control": "no-cache" });
  createReadStream(filePath).pipe(res);
}

function proxy(req, res, backend, urlPath, body) {
  const target = new URL(urlPath, backend);
  const headers = { ...req.headers, host: target.host };
  delete headers["connection"];
  const upstream = http.request(
    target,
    { method: req.method, headers },
    upstreamRes => {
      const isHtml = req.method === "GET" && /text\/html/i.test(upstreamRes.headers["content-type"] || "");
      const chunks = [];
      upstreamRes.on("data", chunk => chunks.push(chunk));
      upstreamRes.on("end", () => {
        const raw = Buffer.concat(chunks);
        if (isHtml) {
          const branded = Buffer.from(rebrand(raw.toString("utf8")), "utf8");
          // The body is now a different size than upstream declared; carry the
          // correct Content-Length or the client truncates to the old length
          // (which cut the HTML mid-tag and crashed the app's render).
          const headers = { ...upstreamRes.headers };
          delete headers["content-encoding"];
          headers["content-length"] = String(branded.length);
          res.writeHead(upstreamRes.statusCode || 200, headers);
          res.end(branded);
        } else {
          res.writeHead(upstreamRes.statusCode || 200, upstreamRes.headers);
          res.end(raw);
        }
      });
    },
  );
  upstream.on("error", error => {
    if (!res.headersSent) res.writeHead(502, { "Content-Type": "text/plain" });
    res.end(`Dareecho brand gateway: backend error: ${error.message}`);
  });
  if (body && body.length) upstream.end(body);
  else upstream.end();
}

export function createBrandGateway({ backend, log = () => {} } = {}) {
  const server = http.createServer((req, res) => {
    const urlPath = req.url || "/";
    log(`REQ ${req.method} ${urlPath}`);
    res.on("finish", () => log(`RES ${res.statusCode} ${req.method} ${urlPath}`));
    // 0. Local single-user auth: the Factory SPA polls /auth/me and expects a
    //    JSON { authenticated, user }. With no auth provider mounted the server
    //    falls through to the HTML index, which the SPA can't parse and loops
    //    on. Serve a stable local user so the studio runs without a sign-in.
    if (req.method === "GET" && urlPath === "/auth/me") {
      const body = JSON.stringify({
        authenticated: true,
        telemetryEnabled: false,
        user: { id: "local", name: "Dareecho", email: "local@dareecho.local" },
      });
      res.writeHead(200, { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" });
      res.end(body);
      return;
    }
    // 1. Brand assets: served directly, same-origin with the UI.
    if (req.method === "GET") {
      const filePath = brandPath(urlPath);
      if (filePath) return serveFile(res, filePath);
    }
    // 2. Everything else: proxy to the Factory server (transform HTML on GET).
    if (req.method === "GET" || req.method === "HEAD") {
      return proxy(req, res, backend, urlPath, null);
    }
    const body = [];
    req.on("data", chunk => body.push(chunk));
    req.on("end", () => proxy(req, res, backend, urlPath, Buffer.concat(body)));
  });

  // WebSocket upgrade: the Factory app opens a live-updates socket through the
  // gateway. A plain HTTP proxy drops the Upgrade handshake and the client
  // hangs on its loading screen, so bridge it to the backend verbatim.
  server.on("upgrade", (req, socket, head) => {
    const target = new URL(req.url || "/", backend);
    const upstream = http.request({
      hostname: target.hostname,
      port: target.port,
      path: `${target.pathname}${target.search}`,
      method: req.method,
      headers: { ...req.headers, host: target.host, connection: "upgrade" },
    });
    upstream.on("upgrade", (upstreamRes, upstreamSocket, upstreamHead) => {
      socket.write(
        `${req.method} ${req.url} HTTP/1.1 101 Switching Protocols\r\n` +
          `Upgrade: websocket\r\nConnection: Upgrade\r\n\r\n`,
      );
      if (upstreamHead && upstreamHead.length) upstreamSocket.unshift(upstreamHead);
      const done = () => {
        if (!upstreamSocket.destroyed) upstreamSocket.destroy();
        if (!socket.destroyed) socket.destroy();
      };
      socket.on("close", done);
      socket.on("error", done);
      upstreamSocket.on("close", done);
      upstreamSocket.on("error", done);
      socket.pipe(upstreamSocket).pipe(socket);
    });
    upstream.on("error", error => {
      socket.write("HTTP/1.1 502 Bad Gateway\r\n\r\n");
      socket.destroy();
    });
    if (head && head.length) upstream.end(head);
    else upstream.end();
  });

  return server;
}

// Run as a script: node apps/factory/brand-gateway.mjs --public 4111 --backend http://127.0.0.1:4112
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const args = parseArgs(process.argv.slice(2));
  const server = createBrandGateway({ backend: args.backend, log: line => console.log(line) });
  server.listen(args.publicPort, args.host, () => {
    console.log(`Dareecho brand gateway on http://${args.host}:${args.publicPort} (backend ${args.backend})`);
  });
}
